import jsPDF from "jspdf";

interface GenerateCertificateProps {
  studentName: string;
  courseName: string;
  completionDate: string;
}

export const generateCertificate = ({
  studentName,
  courseName,
  completionDate,
}: GenerateCertificateProps) => {
  const doc = new jsPDF("landscape", "mm", "a4");

  const pageWidth = 297;
  const pageHeight = 210;

  // Soft warm ivory background
  doc.setFillColor("#fdfcf9");
  doc.rect(0, 0, pageWidth, pageHeight, "F");

  // Delicate top & bottom lines (brushed gold)
  doc.setDrawColor("#c5a663");
  doc.setLineWidth(1);
  doc.line(20, 15, pageWidth - 20, 15);
  doc.line(20, pageHeight - 15, pageWidth - 20, pageHeight - 15);

  // Watermark: subtle large text
  doc.setFont("times", "italic");
  doc.setFontSize(60);
  doc.setTextColor(240, 240, 240);
  doc.text("LearnifyHub", pageWidth / 2, pageHeight / 2, {
    align: "center",
  });

  // Title
  doc.setFont("times", "bold");
  doc.setFontSize(42);
  doc.setTextColor("#2d4059");
  doc.text("Certificate of Completion", pageWidth / 2, 50, {
    align: "center",
  });

  // Small elegant divider
  doc.setDrawColor("#c5a663");
  doc.setLineWidth(0.4);
  doc.line(pageWidth / 2 - 50, 57, pageWidth / 2 + 50, 57);

  // Presented to:
  doc.setFont("helvetica", "normal");
  doc.setFontSize(18);
  doc.setTextColor("#555");
  doc.text("Presented to", pageWidth / 2, 80, { align: "center" });

  // Student name in large serif font
  doc.setFont("times", "bolditalic");
  doc.setFontSize(34);
  doc.setTextColor("#2d4059");
  doc.text(studentName, pageWidth / 2, 100, { align: "center" });

  // For completing the course
  doc.setFont("helvetica", "normal");
  doc.setFontSize(16);
  doc.setTextColor("#555");
  doc.text("for successfully completing the course", pageWidth / 2, 120, {
    align: "center",
  });

  // Course name in contrasting color
  doc.setFont("times", "bold");
  doc.setFontSize(28);
  doc.setTextColor("#c27803");
  doc.text(courseName, pageWidth / 2, 140, { align: "center" });

  // Completion date and time at bottom left
  const currentTime = new Date().toLocaleTimeString();
  doc.setFont("helvetica", "italic");
  doc.setFontSize(12);
  doc.setTextColor("#777");
  doc.text(
    `Date: ${completionDate} | Time: ${currentTime}`,
    20,
    pageHeight - 30
  );

  // Certificate number bottom left
  doc.setFontSize(10);
  doc.text(`Cert ID: LH-${Date.now()}`, 20, pageHeight - 22);

  // Signature line with LearnifyHub signature
  doc.setLineWidth(0.5);
  doc.setDrawColor("#333");
  doc.line(pageWidth - 80, pageHeight - 45, pageWidth - 30, pageHeight - 45);

  // Add LearnifyHub signature above the line
  doc.setFont("times", "italic"); // Stylized signature font
  doc.setFontSize(14);
  doc.setTextColor("#2d4059");
  doc.text("LearnifyHub Admin", pageWidth - 55, pageHeight - 50, {
    align: "center",
  });

  // Label below the signature line
  doc.setFont("helvetica", "italic");
  doc.setFontSize(11);
  doc.setTextColor("#333");
  doc.text("Authorized Signature", pageWidth - 55, pageHeight - 37, {
    align: "center",
  });

  // Small footer line
  doc.setFont("courier", "italic");
  doc.setFontSize(9);
  doc.setTextColor("#aaa");
  doc.text(
    "This certificate is auto-generated by LearnifyHub LMS",
    pageWidth / 2,
    pageHeight - 10,
    {
      align: "center",
    }
  );

  doc.save(`${studentName}-LearnifyHub-Certificate.pdf`);
};
// import jsPDF from "jspdf";

// interface GenerateCertificateProps {
//   studentName: string;
//   courseName: string;
//   completionDate: string;
//   courseLength?: string; // Optional: e.g., "65.5 total hours"
//   instructorName?: string; // Optional: e.g., "Dr. Angela Yu"
// }

// export const generateCertificate = ({
//   studentName,
//   courseName,
//   completionDate,
//   courseLength = "Not specified",
//   instructorName = "LearnifyHub Team",
// }: GenerateCertificateProps) => {
//   const doc = new jsPDF("landscape", "mm", "a4");

//   const pageWidth = 297;
//   const pageHeight = 210;
//   const margin = 15;

//   // Subtle off-white background
//   doc.setFillColor("#f8f9fa");
//   doc.rect(0, 0, pageWidth, pageHeight, "F");

//   // Elegant border (double line: outer gray, inner gold)
//   doc.setDrawColor("#666666");
//   doc.setLineWidth(1);
//   doc.rect(margin, margin, pageWidth - 2 * margin, pageHeight - 2 * margin);
//   doc.setDrawColor("#d4af37"); // Gold
//   doc.setLineWidth(0.3);
//   doc.rect(margin + 2, margin + 2, pageWidth - 2 * margin - 4, pageHeight - 2 * margin - 4);

//   // LearnifyHub Logo (top left)
//   doc.setFont("helvetica", "bold");
//   doc.setFontSize(22);
//   doc.setTextColor("#1a3c5e"); // Deep blue
//   doc.text("LearnifyHub", margin + 5, 30);

//   // Certificate ID (top right)
//   doc.setFont("helvetica", "normal");
//   doc.setFontSize(10);
//   doc.setTextColor("#666666");
//   const certId = `LH-${Date.now().toString(36).substr(-6)}`; // Shorter unique ID
//   doc.text(`Certificate ID: ${certId}`, pageWidth - margin - 5, 30, { align: "right" });

//   // Title: Certificate of Completion
//   doc.setFont("times", "bold");
//   doc.setFontSize(36);
//   doc.setTextColor("#1a3c5e");
//   doc.text("Certificate of Completion", pageWidth / 2, 50, { align: "center" });

//   // Decorative Divider (gold)
//   doc.setDrawColor("#d4af37");
//   doc.setLineWidth(0.5);
//   doc.line(pageWidth / 2 - 60, 55, pageWidth / 2 + 60, 55);

//   // Presented to:
//   doc.setFont("helvetica", "normal");
//   doc.setFontSize(16);
//   doc.setTextColor("#555555");
//   doc.text("Presented to", pageWidth / 2, 75, { align: "center" });

//   // Student Name (large, prominent)
//   doc.setFont("times", "bolditalic");
//   doc.setFontSize(32);
//   doc.setTextColor("#1a3c5e");
//   doc.text(studentName, pageWidth / 2, 95, { align: "center" });

//   // For completing the course
//   doc.setFont("helvetica", "normal");
//   doc.setFontSize(14);
//   doc.setTextColor("#555555");
//   doc.text("For successfully completing the course", pageWidth / 2, 115, { align: "center" });

//   // Course Name (bold, gold)
//   doc.setFont("times", "bold");
//   doc.setFontSize(28);
//   doc.setTextColor("#d4af37");
//   const courseNameLines = doc.splitTextToSize(courseName, pageWidth - 2 * margin - 20);
//   doc.text(courseNameLines, pageWidth / 2, 130, { align: "center" });

//   // Instructor Name (below course name)
//   doc.setFont("helvetica", "normal");
//   doc.setFontSize(12);
//   doc.setTextColor("#666666");
//   doc.text(`Instructor: ${instructorName}`, pageWidth / 2, 150, { align: "center" });

//   // Date, Time, and Length (bottom left)
//   const currentTime = new Date().toLocaleTimeString([], {
//     hour: "2-digit",
//     minute: "2-digit",
//     second: "2-digit",
//   });
//   doc.setFont("helvetica", "italic");
//   doc.setFontSize(12);
//   doc.setTextColor("#777777");
//   doc.text(`Date: ${completionDate}`, margin + 5, pageHeight - 40);
//   doc.text(`Time: ${currentTime}`, margin + 5, pageHeight - 30);
//   doc.text(`Length: ${courseLength}`, margin + 5, pageHeight - 20);

//   // Signature Section (bottom right, dual signatures)
//   doc.setLineWidth(0.5);
//   doc.setDrawColor("#1a3c5e");

//   // Signature 1: Instructor
//   doc.line(pageWidth - margin - 140, pageHeight - 40, pageWidth - margin - 90, pageHeight - 40);
//   doc.setFont("times", "italic");
//   doc.setFontSize(12);
//   doc.setTextColor("#1a3c5e");
//   doc.text("Instructor Signature", pageWidth - margin - 115, pageHeight - 45, { align: "center" });
//   doc.setFont("helvetica", "normal");
//   doc.setFontSize(10);
//   doc.text(instructorName, pageWidth - margin - 115, pageHeight - 35, { align: "center" });

//   // Signature 2: LearnifyHub Admin
//   doc.line(pageWidth - margin - 70, pageHeight - 40, pageWidth - margin - 20, pageHeight - 40);
//   doc.setFont("times", "italic");
//   doc.setFontSize(12);
//   doc.setTextColor("#1a3c5e");
//   doc.text("LearnifyHub Admin", pageWidth - margin - 45, pageHeight - 45, { align: "center" });
//   doc.setFont("helvetica", "normal");
//   doc.setFontSize(10);
//   doc.text("Authorized Signature", pageWidth - margin - 45, pageHeight - 35, { align: "center" });

//   // Footer
//   doc.setFont("helvetica", "italic");
//   doc.setFontSize(8);
//   doc.setTextColor("#aaaaaa");
//   doc.text("This certificate is auto-generated by LearnifyHub LMS", pageWidth / 2, pageHeight - 10, {
//     align: "center",
//   });

//   doc.save(`${studentName}-LearnifyHub-Certificate.pdf`);
// };
